### ISSUE TITLE
When using the ssr service deployed by express, location.reload() is required to switch languages. Is there any way to switch languages on the page without using location.reload?

### ISSUE THREAD

**Issue by AllenIverson1122** [robisim74/qwik-speak#89] opened 2023-09-14 06:32 UTC
The experience would be better if location.reload() was not needed.

**Comment by robisim74** [comment] 2023-09-14 15:05
Duplicate of https://github.com/robisim74/qwik-speak/issues/82

From Qwik [docs](https://qwik.builder.io/docs/api/#link): _Notice that full-page reloads in Qwik are extremely cheap, other frameworks abuse SPA links because a full-page reload requires JS to hydrate and re-execute everything_

However, from [v0.9.0](https://github.com/robisim74/qwik-speak/releases/tag/v0.9.0) of this library context is no longer reactive, the Inline plugin generates a chunks for each language and therefore page reload is required.

See also https://github.com/robisim74/qwik-speak/discussions/37

Greetings

**Closed by robisim74** 2023-09-14 15:05 UTC
Labels: duplicate
